[package]
name = "blog_os"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
edition = "2018"

[dependencies]
bootloader = "0.3.12"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
